linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 25
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: true
        arguments:
          - [] # AllowList
          - [] # DenyList

linters:
  enable-all: true
  disable:
    - dupl
    - exhaustive
    - exhaustivestruct
    - funlen
    - gci
    - gochecknoglobals
    - gocognit
    - goconst
    - gocyclo
    - godot
    - goerr113
    - gofumpt
    - gomnd
    - lll
    - nestif
    - nlreturn
    - wrapcheck
    - wsl
    - nakedret
    - paralleltest
    - testpackage
    - varnamelen
    - tagliatelle
    - nonamedreturns
    - forcetypeassert
    - exhaustruct
    - ireturn
    - cyclop
    - stylecheck
    - errchkjson
    - forbidigo
    - nosnakecase
    - interfacebloat
